---
#info: Add a human user and groups
#https://wiki.debian.org/SystemGroups

# posix
- block:
    - name: Add user '{{ current_user }}'
      user:
        name: '{{ current_user }}'
        password: "{{ current_password | string | password_hash('sha512') }}"
        shell: /bin/bash

    - name: Add users group '{{ current_user }}'
      group:
        name: '{{ current_user }}'
        state: present

    - name: Add user '{{ current_user }}' to groups
      user:
        name: '{{ current_user }}'
        group: '{{ current_user }}'
        groups: '{{ current_groups }}'
        append: yes
  when: '"CYGWIN" not in ansible_os_family'

# windows
#
# When creating a user profile, the user must usually log in via the GUI to
# create the home folder and the registry hive. There is no official way of
# creating a local user profile without a Domain Controller.
# Only adding a user via the terminal and not logging in via the GUI,
# seems to create a bug where the hive regresses into an earlier state.
# Running a command like 'systeminfo', that accesses the hive extensively,
# seems to fix the problem.
# It also needs to run twice, once to create the profile and once to fix it.
- name: Add a new user and create profile
  shell: |
    net user {{ current_user }} {{ current_password }} /add || exit 1
    net localgroup {{ current_groups }} {{ current_user }} /add || exit 1
    systeminfo 1>/dev/null 2>&1 || exit 1
    systeminfo 1>/dev/null 2>&1 || exit 1
  when: '"CYGWIN" in ansible_os_family'