---
#info: Same as cfg_apt, also enable prop, exp and local repo
- name: Set path to script
  set_fact:
    this_task_file: '{{ role_path }}/tasks/cfg_apt.sh'

- include_role: name=servermonkey.sh
  vars:
    sh: '{{ this_task_file }}'
    sh_arg: prop,exp,local