---
#info: Add a human user and groups
#https://wiki.debian.org/SystemGroups
- name: Add user '{{ current_user }}'
  user:
    name: '{{ current_user }}'
    password: "{{ current_pass | password_hash('sha512') }}"
    shell: /bin/bash

- name: Add users group '{{ current_user }}'
  group:
    name: '{{ current_user }}'
    state: present

- name: Add user '{{ current_user }}' to groups
  user:
    name: '{{ current_user }}'
    groups: '{{ current_user }},{{ current_groups }}'
    append: yes