---
#info: Same as cfg_apt, only enable local mounted CD-ROM (CD/DVD/BR) repo for offline use
#info: . Automatically mounts CD-ROM and adds to fstab
- name: Set path to script
  set_fact:
    this_task_file: '{{ role_path }}/tasks/cfg_apt.sh'

- include_role: name=servermonkey.sh
  vars:
    sh: '{{ this_task_file }}'
    sh_arg: offline,cdrom
    sh_nolog: true