---
#info: Same as cfg_apt, also enable expermintal and local repo, for developers
- name: Set path to script
  set_fact:
    this_task_file: '{{ role_path }}/tasks/cfg_apt.sh'

- include_role: name=servermonkey.sh
  vars:
    sh: '{{ this_task_file }}'
    sh_arg: exp,local
    sh_nolog: true