---
#info: Backup each users /home/* folder to a bz2 archive file and copy to host
- name: Backup all /home/* folders
  archive:
    path: /home/*
    dest: '{{ backup_tmp }}'
    exclude_path:
      - /home/ansible
    format: bz2
    mode: 0644

- name: 'Upload backup to {{ ww }}upload/'
  fetch:
    src: '{{ backup_tmp }}'
    dest: '{{ ww }}upload/'
    flat: yes

- name: Delete original backup file
  file:
    path: '{{ backup_tmp }}'
    state: absent