---
#info: Shutdown system (cygwin comp)
- name: Shutdown (Windows)
  shell: "sh -c 'shutdown -s -t 0'"
  when: '"CYGWIN" in ansible_os_family'
  async: 1
  poll: 0

- name: Shutdown (Posix)
  shell: "sh -c 'shutdown -h now'"
  when: '"CYGWIN" not in ansible_os_family'
  become: true
  async: 1
  poll: 0