---
#info: Wait for system to boot
- name: Wait for SSH service to stop
  shell: sleep 20
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  become: false
  run_once: true
  changed_when: false

- name: Poke VM
  shell: virsh -q --connect qemu:///system send-key {{ inventory_hostname }} 0x1
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  when: '"CYGWIN" in ansible_os_family'

- name: Wait for connection
  wait_for_connection:
    connect_timeout: 300
    sleep: 3
    delay: 0
    timeout: 300