---
#info: Test if a machine is online and gather facts (cygwin comp)
#use: Needs to be run on newly added systems
- block:
    - name: Check network connection
      wait_for_connection:
        timeout: 5
      register: info_test_error
      become: true

    - name: Ansible Ping
      ping:

    - name: Gather facts
      setup:
  become: true

  rescue:
    - include_role: name=servermonkey.ww_logger
      vars:
        ww_msg: 'Unreachable: {{ info_test_error.msg }}'
        ww_logfile: servermonkey.ww_info_test