---
#info: Check for an open SSH port on 'ansible_host' (IP not hostname)
#info: , show OK if successful, ignore errors
- set_fact:
    info_test_ssh_current_host: "{{ ansible_host }}"

- name: Test port 22 (portscan)
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  shell: |
    nc -z -w5 {{ info_test_ssh_current_host }} 22 &&
    echo OK
  register: shell
  async: 60
  poll: 0
  throttle: 20
  become: false
  failed_when: false

- name: Check on an async task
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  async_status:
    jid: '{{ shell.ansible_job_id }}'
  register: job
  until: job.finished
  retries: 1000
  delay: 3
  become: false

- include_role: name=servermonkey.ww_logger
  vars:
    ww_msg: '{{ job.stdout }}'
    ww_logfile: 'servermonkey.ww_info_test-ssh-inverse'