---
#info: Simple ICMP network ping
- name: ICMP Ping
  connection: local
  shell: ping4 -W 3 -c 1 {{ ansible_host }} 2>/dev/stdout 1>/dev/null || true
  register: info_ping_shell

- include_role: name=servermonkey.ww_logger
  vars:
    ww_msg: '{{ info_ping_shell.stdout }}'
    ww_logfile: servermonkey.ww_info_ping