---
#info: Install generic Desktop/office packages that are not in install_xfce
- name: Install basic Desktop packages
  package:
    update_cache: yes
    name:
      - synaptic  # package manager
      - firefox-esr
      - webext-ublock-origin-firefox
      - doublecmd-common  # advanced file manager
      - meld  # diff viewer
      - p7zip-full
      - geany  # better text editor

- name: Set Firefox as default browser
  shell: xdg-settings set default-web-browser firefox-esr.desktop
  become_user: '{{ current_user }}'
  changed_when: false

- name: Install generic Desktop packages
  package:
    name:
      - libreoffice-gtk3
      - libreoffice-base
      - libreoffice-calc
      - libreoffice-draw
      - libreoffice-impress
      - libreoffice-math
      - thunderbird
      - quodlibet  # music player
      - webext-privacy-badger  # stop trackers
      - transmission-gtk  # torrents
      - unison  # best file syncronisation tool
      - unison-gtk
      - syncthing  # live file synchronisation, works well with Android
      - syncthing-gtk
      - borgbackup  # backup tool
      - vorta  # GUI for borgbackup
      - doublecmd-help-en
      - libffmpegthumbnailer4v5  # thumbnails in doublecmd
      - libunrar5  # extract rar in doublecmd
      - keepassxc  # password manager
      - speedcrunch  # calculator
      - filezilla  # FTP client
      - evince  # view docs: PDF, PS, EPS, DjVu, DVI, XPS
      - catfish  # search files
      - gpick  # pick colors
      - ristretto  # image viewer
      - converseen  # batch image converter
      - flameshot  # better screenshot tool
      - persepolis  # download manager
      - pidgin  # chat application
  when: install_desktop_minimal == false

- name: Install printing system
  package:
    name: system-config-printer  # graphical interface to configure the printing system
  when: ansible_virtualization_role != 'guest'

- name: Detect if WIFI is available
  shell: iw dev | grep Interface | awk '{print $2}'
  register: shell_install_desktop_has_wifi
  failed_when: shell_install_desktop_has_wifi.rc != 0
  changed_when: false

- name: Install network-manager if WIFI is available
  package:
    name:
      - network-manager-gnome  # let users manage networks, like WIFI, also enables tray icon in XFCE
  when:
    - install_desktop_minimal == false
    - shell_install_desktop_has_wifi.stdout != ""

- name: Detect GPU
  script: detect-gpu.sh
  register: install_desktop_detect_gpu
  failed_when: '"Failed" in install_desktop_detect_gpu.stdout'
  changed_when: false

- name: Install QXL GPU driver and SPICE agent on VMs
  package:
    name:
      - xserver-xorg-video-qxl
      - spice-vdagent
  when:
    - "'QXL' in install_desktop_detect_gpu.stdout"
    - "ansible_virtualization_role == 'guest'"