---
#info: Install KVM and Vagrant with default network config
- name: Install KVM and Vagrant
  package:
    update_cache: yes
    name:
      - qemu-kvm  # base hypervisor
      - libvirt-clients  # will install lvm2, ignore lvmconfig failed errors, fixed after reboot
      - libvirt-daemon-system  # autostart hypervisor as system service
      - virt-manager  # GUI manager
      - bridge-utils
      - vagrant-libvirt
      - python3-lxml  # let's Ansible modify VM's XML configs, for KVM configs

- name: Add user '{{ current_user }}' to libvirt
  user:
    name: '{{ current_user }}'
    groups: libvirt
    append: yes
  when: install_libvirt_allow_current_user

- name: Set libvirt default connect URI
  lineinfile:
    path: '/etc/libvirt/libvirt.conf'
    line: 'uri_default = "qemu:///system"'

- name: Start KVM network
  shell: |
    virsh net-autostart default
    virsh net-start default || true
  changed_when: false

#todo: find out why "lvmcinfig" faile during installation, install each package separate