---
#info: Packages that should exist on every system, additional sysadmin tools
- name: Install additional sysadmin command line tools
  package:
    update_cache: yes
    name:
      - mutt  # read and manage system mail
      - ccze  # colorize shell output
      - apt-xapian-index  # search packages with 'axi-cache search ...'
      - tldr  # simplified man pages
      - dtrx  # better package extractor
      - ncdu  # disk usage
      - trash-cli  # trash utility
      - locate  # find files fast, a file indexter
      - tree  # tree directory
      - curl  # alternative to wget
      - visidata  # table editor
      - iftop  # display bandwidth usage
      - ipcalc  # IPv4 Netmask/broadcast/etc calculator

- name: Update xapian index
  shell: update-apt-xapian-index -u
  register: base_extra_xapian
  changed_when: '"is up to date" not in base_extra_xapian.stderr'

- name: Update locate database
  shell: updatedb
  register: base_extra_updatedb
  changed_when: false