---
#info: Generic installation, use as a baseline, latest upgrades (reqires Internet)
#info: , Good to run before any other major task
- include_role: name=servermonkey.ww
  vars:
    task: '{{ loop_setup_generic }}'
  loop:
    - cfg_apt
    - do_upgrade
    - cfg_ntp
    - install_base
    - cfg_hostname
    - cfg_locales
    - cfg_grub-faster
    - cfg_auto-upgrades
  loop_control:
    loop_var: loop_setup_generic

- include_role: name=servermonkey.ww
  vars:
    task: cfg_raspberry-pi
  when: '"RASPIROOT" in ansible_cmdline.root'