---
#info: Generic installation, use as a baseline
#info: , Good to run before any other major task like 'setup_' or 'install_'
- include_role: name=servermonkey.ww
  vars:
    task: '{{ loop_setup_generic }}'
  loop_control:
    loop_var: loop_setup_generic
  loop:
    - info_test-or-fail
    - info_test-become
    - cfg_network
    - 'cfg_apt-{{ cfg_apt_repos }}'
    - cfg_bash
    - cfg_dis-beep
    - cfg_dis-me
    - do_upgrade
    - cfg_ntp
    - install_base
    - cfg_hostname
    - cfg_locales
    - cfg_boot-faster
    - cfg_auto-upgrades
    - cfg_theme-windows
    - autorun_set-resolution

- block:
    - include_role: name=servermonkey.ww
      vars:
        task: cfg_raspberry-pi
      when: '"RASPIROOT" in ansible_cmdline.root'
  when: '"CYGWIN" not in ansible_os_family'